# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a200e064e607aa6c40baabd6be3a152343e60d09ddb4b42efbd2a0f92abe27657c222d2c4c542b324dd502d9985e35fc629ceef106aeb25c5169e2e27b097e2d

test:
  secret_key_base: f43b840f1833fb8ba79d4685182463a36c54d0bf53b13f89f139a3f11fde0c56f4b195b5c0b75a3a9a0bd57f64374f182dd3840a9f7a5ff7b3df741230ddb3a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
